# Generated by Django 3.2.7 on 2021-10-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sensor ID'),
        ),
    ]
